feat: :sparkles: Feita a função "verResumo" e "verProdutosComprados" …
jairrcarvalho/koru-mobile-projeto-3 pull request #36
Opened 2024-04-16 19:59 UTC by wellingtonzero21

…na calsse cliente e revendedor

Foi feita funções de resumos, "verResumo" e "verProdutosComprados" na calsse cliente e revendedor na qual mostra todas as informações resumidas.

2024-04-16 20:07 UTC, MarcosBenHurSilva approved these changes
Tudo ok.

2024-04-16 20:10 UTC, queirozmat requested changes
Já exite uma função para calcular media e o arrendondamento tem que ser feio nas funções calcularTotalVendido() , calcularLucro(), e na calcularMediaProdutosVendidos(). E esse try catch é desnecessario. 

obs: não tem problema algum deixar o arrendondamento novamente quando for fazer o print. Mas se caso tiver sido feito nas funções seria irelevante.

2024-04-16 20:12 UTC, queirozmat requested changes
No metodo verProdutosComprados() seria interessante ordernar os produtos antes de Exibilos pois é o que o metodo pede.

2024-04-17 01:02 UTC, queirozmat approved these changes
ok.

2024-04-17 01:48 UTC, jairrcarvalho approved these changes
Ótimo.

2024-04-17 17:54 UTC, merged